services:
  - type: web
    name: rag-chatbot-dc-office
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: UVICORN_PORT
        value: 10000
